### ISSUE TITLE
Dual monitor not working

### ISSUE THREAD

**Issue by szakitom** [alexpotter1/intel-nuc6i7kyk-opencore#2]
Hello,
First of all thanks for the awesome project.

I can't get dual monitors to work. I have a monitor attached with miniDP and HDMI as well. If both are connected after boot only the hdmi one works, but I can see both of them in system preferences.
If I only connect miniDP then if works but the system crashes if I connect the HDMI after.

Is there a way to enable both displays?

Thank you

**Comment by alexpotter1** [comment]
Hi,

Issues regarding dual monitors were fixed with a182e791d6cc0b7d306c95f4f57cf5cd0fba059e, but there is a chance your configuration may be different to what is expected.

Can you post a copy of your IOReg - use [this](https://github.com/vulgo/IORegistryExplorer/releases) tool to dump it

Thanks

**Comment by szakitom** [comment]
Sure
[Skull.ioreg.zip](https://github.com/alexpotter1/intel-nuc6i7kyk-opencore/files/4793936/Skull.ioreg.zip)

**Comment by szakitom** [comment]
Aftern resetting the NVRAM everything seems to be working fine, will report back in a few days.

Thanks again for the awesome work

**Comment by alexpotter1** [comment]
> Aftern resetting the NVRAM everything seems to be working fine, will report back in a few days.
> 
> Thanks again for the awesome work

Interesting. I did take a quick look at your IOReg and nothing seemed out of the ordinary.

Maybe it's worth adding to the README to clear NVRAM in case of issues

Thanks for the feedback
