### ISSUE TITLE
Handoff / Continuity Support

### ISSUE THREAD

**Issue by ghost** [alexpotter1/intel-nuc6i7kyk-opencore#7]
Hi Alex, 

I was wondering if there is any chance to patch the Handoff / Continuity support with the Intel NUC?
I have temporarily tried using the HeliPort WiFi but Handoff is still not showing up my iPad Pro which is connected via cable...

Any hint would be appreciated :-)

Thanks again!

**Comment by alexpotter1** [comment]
Hi

itlwm doesn't currently implement the closed-source Apple IO80211Family API, so there's no Handoff/Continuity support.
If you require this feature, you should use a natively-supported Broadcom WiFi chipset. 

I don't have said WiFi card myself, so I can't really suggest which one to get unfortunately.

Thanks
